checkver:
  type: script
  script: |
    try {
        $Response = Invoke-WebRequest -Uri 'https://blitz.gg/download/win' -MaximumRedirection 0
    } catch {
        $_.Exception.Response.Headers.Location.OriginalString
    }
  regex: "([\\d.]+).exe"

installerUrlTemplate: "https://blitz-main.blitz.gg/Blitz-{version}.exe"
