checkver:
  type: script
  regex: Ham Radio Deluxe.*?v([\d.]+)
  script: |
    $response = Invoke-WebRequest -Uri "https://hamradiodeluxe.com/downloads" -UseBasicParsing
    Write-Output $response.Content

installerUrlTemplate: "https://downloads.hamradiodeluxe.com/setupHRD_{versionNoDots}.exe"
