checkver:
  type: script
  script: |
    $output = & wget -qO- "https://dev.mysql.com/downloads/mysql/#info-tab" 2>&1
    Write-Output $output
  regex: ">([\\d.]+) LTS<"

installerUrlTemplate: "https://cdn.mysql.com/Downloads/MySQL-{versionMajorMinor}/mysql-{version}-winx64.msi"
