checkver:
  type: github
  repo: pbatard/rufus

installerUrlTemplate:
  x86: "https://github.com/pbatard/rufus/releases/download/v{version}/rufus-{version}_x86.exe"
  x64: "https://github.com/pbatard/rufus/releases/download/v{version}/rufus-{version}.exe"
  arm64: "https://github.com/pbatard/rufus/releases/download/v{version}/rufus-{version}_arm64.exe"
